name: (base) Build and Deploy to Firebase Preview channel

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_env_command:
        required: true
        type: string
      projectId:
        required: true
        type: string
      channel:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      firebaseServiceAccount:
        required: true
      gitToken:
        required: true


jobs:
  build_and_deploy_preview_channel:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - run: npm ci
      - run: npm run ${{ inputs.build_env_command }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.gitToken }}
          firebaseServiceAccount: ${{ secrets.firebaseServiceAccount }}
          projectId: ${{ inputs.projectId }}
          channelId: ${{ inputs.channel }}
