name: (base) Build and Deploy to Firebase project

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_env_command:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      FIREBASE_CI_TOKEN:
        required: true

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ inputs.build_env_command }}
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  deploy:
    needs: build_project
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: 'npm'
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: npm i -g firebase-tools
      - run: firebase deploy --token ${{ secrets.FIREBASE_CI_TOKEN }} --project ${{ inputs.project }}
