name: (staging) Build and deploy to firebase channel

on:
  workflow_dispatch:
    inputs:
      channel:
        description: Channel name
        required: true
        type: string
      branch:
        description: Target branch
        required: true
        type: string

jobs:
  build_and_deploy:
    uses: psgamer/partners-portal/.github/workflows/build_and_deploy_to_firebase_channel_base.yml@staging
    with:
      environment: staging
      build_env_command: build_staging
      projectId: eset-partners-portal-staging
      channel: ${{ inputs.channel }}
      branch: ${{ inputs.branch }}
    secrets:
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESET_PARTNERS_PORTAL_STAGING }}
      gitToken: ${{ secrets.GITHUB_TOKEN }}
