name: (staging) Build and deploy to firebase project

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    uses: psgamer/sample-project/.github/workflows/build_and_deploy_to_firebase_project_base.yml@staging
    with:
      environment: staging
      build_env_command: build_staging
      project: eset-partners-portal-staging
    secrets: inherit
